from __future__ import annotations

from scenethesis_mvp.schemas.asset import AssetSpec


REQUIRED_PROCEDURAL_CATEGORIES = {
    "table",
    "shelf",
    "chair",
    "box",
    "cylinder",
    "robot_arm",
    "cabinet",
    "tool",
    "monitor",
    "bin",
}


CATEGORY_ALIASES = {
    "bench": "table",
    "workbench": "table",
    "desk": "table",
    "rack": "shelf",
    "racks": "shelf",
    "shelving": "shelf",
    "storage_shelf": "shelf",
    "storage_shelves": "shelf",
    "storage": "shelf",
    "seat": "chair",
    "stool": "chair",
    "crate": "box",
    "cardboard_box": "box",
    "container": "container",
    "storage_container": "container",
    "jerrycan": "container",
    "jerry_can": "container",
    "jerry_cans": "container",
    "fuel_can": "container",
    "fuel_cans": "container",
    "cement_bag": "bag",
    "cement_bags": "bag",
    "bag": "bag",
    "bags": "bag",
    "barrel": "cylinder",
    "barrels": "cylinder",
    "drum": "cylinder",
    "drums": "cylinder",
    "canister": "cylinder",
    "handtruck": "hand_truck",
    "hand_truck": "hand_truck",
    "dolly": "hand_truck",
    "cart": "cart",
    "trolley": "cart",
    "trolleys": "cart",
    "robot": "robot_arm",
    "arm": "robot_arm",
    "robotic_arm": "robot_arm",
    "fork_lift": "forklift",
    "forklift": "forklift",
    "forklifts": "forklift",
    "pallet": "pallet",
    "pallets": "pallet",
    "pallet_load": "pallet_load",
    "pallet_loads": "pallet_load",
    "wrapped_pallet": "pallet_load",
    "wrapped_pallets": "pallet_load",
    "barcode_scanner": "scanner",
    "scanner": "scanner",
    "scanners": "scanner",
    "floor_tape": "floor_marking",
    "safety_tape": "floor_marking",
    "floor_marking": "floor_marking",
    "drawer": "cabinet",
    "cupboard": "cabinet",
    "toolbox": "tool",
    "tool_box": "tool",
    "tool_chest": "cabinet",
    "wrench": "tool",
    "screwdriver": "tool",
    "pliers": "tool",
    "crowbar": "tool",
    "sledgehammer": "tool",
    "hammer": "tool",
    "measuring_tape": "tool",
    "bolt_cutters": "tool",
    "screen": "monitor",
    "display": "monitor",
    "trash_bin": "bin",
    "basket": "bin",
    "safety_barrier": "barrier",
    "concrete_barrier": "barrier",
    "fence": "barrier",
    "chainlink": "barrier",
    "chain_link": "barrier",
    "security_camera": "camera",
    "surveillance_camera": "camera",
    "cables": "cable",
    "electric_cables": "cable",
}


DEFAULT_CATEGORY_COLORS: dict[str, tuple[float, float, float]] = {
    "table": (0.55, 0.36, 0.20),
    "shelf": (0.42, 0.42, 0.40),
    "chair": (0.25, 0.35, 0.55),
    "box": (0.68, 0.49, 0.28),
    "cylinder": (0.35, 0.58, 0.62),
    "robot_arm": (0.86, 0.55, 0.16),
    "cabinet": (0.36, 0.40, 0.45),
    "tool": (0.12, 0.12, 0.12),
    "monitor": (0.05, 0.06, 0.07),
    "bin": (0.18, 0.47, 0.35),
    "forklift": (0.95, 0.48, 0.08),
    "pallet": (0.56, 0.36, 0.18),
    "pallet_load": (0.72, 0.70, 0.62),
    "cart": (0.50, 0.52, 0.50),
    "scanner": (0.06, 0.06, 0.06),
    "barrier": (0.95, 0.42, 0.06),
    "floor_marking": (0.95, 0.72, 0.06),
}


def normalize_category(category: str) -> str:
    key = category.strip().lower().replace(" ", "_").replace("-", "_")
    return CATEGORY_ALIASES.get(key, key)


def asset_color(asset: AssetSpec) -> tuple[float, float, float]:
    return asset.color or DEFAULT_CATEGORY_COLORS.get(asset.category, (0.6, 0.6, 0.6))
